=== gregkonush/lab/schemas/custom/argoproj.io_v1alpha1_Sensor.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "urn:argoproj.io:v1alpha1:Sensor",
  "type": "object",
  "properties": {
    "apiVersion": {
      "type": "string"
    },
    "kind": {
      "type": "string"
    },
    "metadata": {
      "type": "object"
    },
    "spec": {
      "type": "object",
      "x-kubernetes-preserve-unknown-fields": true
    },
    "status": {
      "type": "object",
      "x-kubernetes-preserve-unknown-fields": true
    }
  },
  "required": [
    "metadata",
    "spec"
  ],
  "additionalProperties": true,
  "definitions": {}
}

=== gregkonush/lab/tmp.json
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "argocd.argoproj.io/sync-wave": "-1",
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{\"argocd.argoproj.io/sync-wave\":\"-1\"},\"labels\":{\"argocd.argoproj.io/instance\":\"root\"},\"name\":\"longhorn-system\"}}\n"
        },
        "creationTimestamp": "2024-09-22T06:14:55Z",
        "deletionTimestamp": "2024-09-22T07:39:56Z",
        "labels": {
            "argocd.argoproj.io/instance": "root",
            "kubernetes.io/metadata.name": "longhorn-system"
        },
        "name": "longhorn-system",
        "resourceVersion": "4869507",
        "uid": "d4084882-0fca-46f7-a18e-aeb0319bfb4d"
    },
    "spec": {
        "finalizers": []
    },
    "status": {
        "conditions": [
            {
                "lastTransitionTime": "2024-09-22T07:40:07Z",
                "message": "All resources successfully discovered",
                "reason": "ResourcesDiscovered",
                "status": "False",
                "type": "NamespaceDeletionDiscoveryFailure"
            },
            {
                "lastTransitionTime": "2024-09-22T07:40:07Z",
                "message": "All legacy kube types successfully parsed",
                "reason": "ParsedGroupVersions",
                "status": "False",
                "type": "NamespaceDeletionGroupVersionParsingFailure"
            },
            {
                "lastTransitionTime": "2024-09-22T07:40:07Z",
                "message": "Failed to delete all resource types, 1 remaining: unexpected items still remain in namespace: longhorn-system for gvr: /v1, Resource=pods",
                "reason": "ContentDeletionFailed",
                "status": "True",
                "type": "NamespaceDeletionContentFailure"
            },
            {
                "lastTransitionTime": "2024-09-22T07:40:07Z",
                "message": "Some resources are remaining: pods. has 8 resource instances",
                "reason": "SomeResourcesRemain",
                "status": "True",
                "type": "NamespaceContentRemaining"
            },
            {
                "lastTransitionTime": "2024-09-22T07:51:49Z",
                "message": "All content-preserving finalizers finished",
                "reason": "ContentHasNoFinalizers",
                "status": "False",
                "type": "NamespaceFinalizersRemaining"
            }
        ],
        "phase": "Terminating"
    }
}
